### ISSUE TITLE
<p> with tab rather than spaces

### ISSUE THREAD

**Issue by tobydriscoll** [oscarlevin/vscode-pretext#1]
This extension has become integral for some course notes I am writing. The only thing I would want to change is that a paragraph element insert a tab rather than two spaces. All the other indentation I do uses tabs, so this messes up the scheme overall.

**Comment by oscarlevin** [comment]
This should be fixed if you update to 0.2.0.  I convert tabs to spaces anyway, so didn't realize this was inconsistent.  Fixed a lot of other places too.  Thanks for bringing it to my attention.
